In [2]:
import pandas as pd

In [5]:
oecd = pd.read_csv("../data/oecd_bli.csv", thousands=',')

In [6]:
oecd.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,...,OBS_VALUE,Observation Value,OBS_STATUS,Observation Status,UNIT_MEASURE,Unit of Measures,UNIT_MULT,Multiplier,BASE_PER,Base reference period
0,DATAFLOW,OECD:DF_BLI(1.0),Better Life Index,I,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,...,2.3,NaN,A,NaN,PC,Percentage,0,Units,NaN,NaN
1,DATAFLOW,OECD:DF_BLI(1.0),Better Life Index,I,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,...,2.4,NaN,A,NaN,PC,Percentage,0,Units,NaN,NaN
2,DATAFLOW,OECD:DF_BLI(1.0),Better Life Index,I,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,...,3.8,NaN,A,NaN,PC,Percentage,0,Units,NaN,NaN
3,DATAFLOW,OECD:DF_BLI(1.0),Better Life Index,I,CZE,Czechia,JE_LMIS,Labour market insecurity,L,Value,...,2.3,NaN,A,NaN,PC,Percentage,0,Units,NaN,NaN
4,DATAFLOW,OECD:DF_BLI(1.0),Better Life Index,I,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,...,4.5,NaN,A,NaN,PC,Percentage,0,Units,NaN,NaN

In [11]:
gdp_per_capita = pd.read_csv("../data/gdp_per_capita.csv", low_memory=False, thousands=',')
gdp_per_capita.head()

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,UNIT,COUNTRY_UPDATE_DATE,PUBLICATION_DATE,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),GBR.NGDPD.A,OBS_VALUE,United Kingdom,"Gross domestic product (GDP), Current prices, ...",Annual,Billions,US dollar,9/13/2025,2026-04-14T13:00:00Z,...,3192.851,3422.072,3695.355,4003.022,4264.794,4466.076,4675.048,4898.448,5148.434,5403.155
1,IMF.RES:WEO(9.0.0),GBR.PCPI.A,OBS_VALUE,United Kingdom,"All Items, Consumer price index (CPI), Period ...",Annual,Units,Index,9/13/2025,2026-04-14T13:00:00Z,...,121.665,130.550,133.853,138.368,142.800,146.253,149.178,152.161,155.205,158.309
2,IMF.RES:WEO(9.0.0),ITA.LP.A,OBS_VALUE,Italy,"Population, Persons for countries / Index for ...",Annual,Millions,NaN,9/23/2025,2026-04-14T13:00:00Z,...,59.030,58.997,58.971,58.934,58.879,58.806,58.716,58.611,58.493,58.364
3,IMF.RES:WEO(9.0.0),LIE.LE.A,OBS_VALUE,"Liechtenstein, Principality of","Employed persons, Persons for countries / Inde...",Annual,Millions,NaN,9/29/2025,2026-04-14T13:00:00Z,...,0.043,0.043,0.043,0.044,0.044,0.045,NaN,NaN,NaN,NaN
4,IMF.RES:WEO(9.0.0),GBR.GGXONLB.A,OBS_VALUE,United Kingdom,"Primary net lending (+) / net borrowing (-), G...",Annual,Billions,Domestic currency,9/13/2025,2026-04-14T13:00:00Z,...,-26.845,-101.457,-116.298,-83.997,-38.632,-12.753,8.109,36.219,48.305,50.306